spring:
  application:
    name: backend-meetcode
  security:
    user:
      name: admin
      password: password
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?user=postgres.pyutsvbzmnsxgwxtauxq&password=12345678910qwertyuioasdfjuyvtvvtjvtytrvt
    username: postgres
    password: 12345678910qwertyuioasdfjuyvtvvtjvtytrvt
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    websocket:
      path: /graphql
    cors:
      allow-credentials: true
      allowed-origins: http://localhost:3000,https://dsa-colab-frontend.vercel.app

server:
  port: 8081

jwt:
  secret: thisisaverysecurejwtsecretkeymustbe32chars
  expiration: 86400000
  refresh-token:
    expiration: 604800000